---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql-deployment
  labels: 
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: eazytraining
            - name: MYSQL_USER
              value: eazy
            - name: MYSQL_PASSWORD
              value: eazy
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data-mysql
      volumes:
      - name: data-mysql
        hostPath:
          path: /data-mysql
          type: Directory
