---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wordpress-deployment
  labels: 
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: service-clusterip-web
            - name: WORDPRESS_DB_NAME
              value: eazytraining
            - name: WORDPRESS_DB_USER
              value: eazy
            - name: WORDPRESS_DB_PASSWORD
              value: eazy
          volumeMounts:
            - mountPath: /var/www/html
              name: data-wp
      volumes:
      - name: data-wp
        hostPath:
          path: /data-wp
          type: Directory
