---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp-deployment
  labels: 
    app: myapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-myapp
          image: nginx:latest
          ports:
            - containerPort: 80
