---
kind: Pod
apiVersion: v1
metadata:
  name: simple-webapp-color
spec:
  containers:
  - name: web
    image: mmumshad/simple-webapp-color
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: red
